name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login
      run: docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME}}"  -p "${{ secrets.DOCKER_TOKEN}}"
    - name: Build
      run: docker build -t lanbuntu:v1.0 .   
    - name: Push
      run: docker push /james-martinez/ubuntu/lanbuntu:v1.0
