name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker
      run: docker login -u "${{ secrets.DOCKER_USERNAME}}"  -p "${{ secrets.DOCKER_TOKEN}}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ secrets.DOCKER_IMAGE_TAG}}"
    - name: Push the Docker image
      run: docker push "${{ secrets.DOCKER_IMAGE_TAG}}"
