name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login
      run: docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME}}"  -p "${{ secrets.DOCKER_TOKEN}}"
    - name: Build
      run: $ docker build -t docker.pkg.github.com/james-martinez/ubuntu/lanbuntu:latest .   
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/james-martinez/ubuntu/lanbuntu:latest
